//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusNews_PortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int Id { get; set; }
        public Nullable<int> CurrentBalalnce { get; set; }
        public Nullable<int> RequiredBudget { get; set; }
        public Nullable<int> BudgetStatus { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }
}
