//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndusNews_PortalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int CVId { get; set; }
        public string CVFileName { get; set; }
        public string CVContentType { get; set; }
        public byte[] CVFile { get; set; }
        public Nullable<int> ApplicantId { get; set; }
    
        public virtual JobApplicant JobApplicant { get; set; }
    }
}
